version: '3.8'

services:
  front:
    build: ./front/to-do app
    ports:
      - "5173:5173"
    depends_on:
    - api

  api:
    build: ./back
    ports:
      - "3002:3002"
    depends_on:
    - mongo
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
